### ISSUE TITLE
Nome dos arquivos e funções no diretório models

### ISSUE THREAD

**Issue by fboldt** [lucioventurim/ISIE_2021#1]
A divisão ficou boa. A ideia de implementar um função para retornar um modelo com pipeline e gridsearch também é boa.
O nome das funções e dos arquivo não está bom.
Acho que os nomes deveriam ser algo como "instantiate_auto_knn" e "instantiate_auto_random_forest", ou "instantiateAutoKnn" e "instantiateAutoRandomForest", ou outra forma que você achar melhor. 
O importante é manter a coerência e informar precisamente o que a função faz e onde posso encontrar essa função. 
Pode ser que o nome do arquivo seja "auto_knn.py", ou outro nome que você achar melhor. "knn.py" está ruim.

**Comment by lucioventurim** [comment]
Itens renomeados Professor. Incluí também um CNN mas ainda estou desenvolvendo.

**Comment by fboldt** [comment]
A divisão ficou boa, mas o arquivo classifiers.py não. Sugiro excluir este arquivo.
Se você quer uma forma para facilitar o uso de vários classificadores, sugiro mudar o nome do diretório para 'classification_models' e transformar este diretório em um pacote: https://packaging.python.org/tutorials/packaging-projects/

**Comment by lucioventurim** [comment]
arquivos renomeados seguindo o padrão discutido.
