### ISSUE TITLE
Excluir o arquivo e a classe Experimenter

### ISSUE THREAD

**Issue by fboldt** [lucioventurim/ISIE_2021#2]
A segmentação varia de acordo com a base. Não faz sentido colocar uma classe genérica para segmentar.
Os experimentos são específicos de cada base e devem ser planejados de acordo com o que se quer demonstrar.
Por isso, tem que se criar um arquivo para cada combinação dessas. 
O nome do arquivo poderia ser algo parecido com "similarity_bias_mfpt.py" e as funções poderiam ter nomes tipo "usualKfoldMfpt" e "unbiasedGroupKfoldMfpt", ou outro nome que você achar melhor.

**Comment by lucioventurim** [comment]
No caso as aquisições são extraídas para um formato padrão em um dicionário onde cada aquisição tem uma identificação.
Dessa forma, você acha interessante termos um "segmentator" onde são passadas como entrada esse dicionário e o tamanho da amostra desejada? Coloquei assim no código para você conferir. Podemos também se quisermos colocar outros parâmetros de entrada nesse segmentador, como sobreposição, etc.

**Comment by fboldt** [comment]
Colocar as aquisições em um dicionário não é uma boa solução, e não funciona para bases grandes. O software tem que funcionar para bases pequenas e grandes.
Ter um segmentador não é bom. Ele devolve a base toda segmentada de uma vez, o que não vai funcionar para bases grandes.
Quanto menos parâmetros melhor.
A base tem que saber como ela deve ser dividida. Para fazer as folds, você pode usar o recurso yield do python: http://devfuria.com.br/python/yield/

**Comment by lucioventurim** [comment]
código alterado, excluindo a classe experimenter e utilizando o yield para o fornecimento das folds.
