### ISSUE TITLE
Imprimir os resultados não é uma boa solução

### ISSUE THREAD

**Issue by fboldt** [lucioventurim/ISIE_2021#3]
Imagine que todos os seus experimentos já rodaram, mas você ainda não olhou para a tela, e a energia acabou!
Perdeu tudo!
Isso é um exemplo bobo. Mas a pior parte é que você não consegue aproveitar nada via código dos resultados que você obteve. Vai precisar intervir manualmente. Isso é contra-produtivo.
Para mim, a melhor solução é retornar um vetor com y_actual e y_predicted.
Assim, você consegue calcular a métrica que você quiser depois de ter rodado o exprimento.

Mais um exemplo:
Imagine que você rodou e salvou em arquivos os resultados de acurácia e f-measure.
Submeteu o artigo e um revisor pediu para colocar precisão e revocação também!
Vai ter que rodar tudo de novo.
Se você tiver y_actual e y_predicted, pode calcular as novas métricas sem precisar rodar os experimentos de novo.

Ainda melhor seria se você conseguisse retornar Y-actual, y_predicted e confidence (ou probability). 
Com isso você consegue calcular inclusive ROC_AUC e precision recall curves.

**Comment by lucioventurim** [comment]
Alterei o kfold para salvar em um arquivo texto os y_actual e o y_pred de cada fold. Confere se assim ficou bom
Vou colocar para salvar o confidence também

**Comment by fboldt** [comment]
Ainda não ficou bom.
A melhor solução é retornar um numpy array. Ele pode ter 3 dimensões, onde a 3ª é o fold.
Padronizando isso, você pode depois fazer uma função que converte esses arrays para arquivos de texto, ou simplesmente gravá-los em binário, como um pickle.
Vocẽ não precisa da função (e nem do arquivo) performer.
OBS.: Eu tive que acertar o código para rodar. Por favor, confira no terminal se o código está rodando antes de fazer o push.

**Comment by lucioventurim** [comment]
inserido funcionalidade para salvar em um pickle. pendente incluir também o confidence interval.

**Comment by fboldt** [comment]
Use csv ou json.
