### ISSUE TITLE
Um bom número de folds para MFPT seria 3

### ISSUE THREAD

**Issue by fboldt** [lucioventurim/ISIE_2021#4]
A base MFPT tem 3 aquisições para a condição normal.
É uma boa justificativa para usar 3 folds.
Quanto aos grupos, podem ser aleatórios ou fixos.
Sugiro fixos para simplificar e facilitar a replicabilidade dos experimentos.

**Comment by lucioventurim** [comment]
Coloquei com 3 folds no código.
Com relação aos grupos, não entendi a definição de aleatórios ou fixos. Você quis dizer com relação à escolha de quais grupos serão utilizados para treino e quais para teste? (nas condições com mais de três aquisições)

**Comment by fboldt** [comment]
Como você está garantindo que sempre exista pelo menos um exemplo de cada classe na fold de treinamento?
Você pode ter classes faltantes no teste, mas não no treino.
Por sorte (ou azar) a forma que no GroupKFold é implementado manteve essa premissa para o MFPT. Mas isso não será garantido para outras bases, ou para esta mesma base reduzida.
Você consegue me mostrar no código atual como ficaram divididas as aquisições quando você usou o groupkfold?
Você vai conseguir me responder isso facilmente quando se livrar dessa função segmentator, que foi uma péssima ideia.
Daí você poderá distribuir os grupos de cada base, de acordo com suas características específicas.
No caso da MFPT, dá pra fazer várias divisões de 3 folds diferentes. Mas essas divisões precisam ter pelo menos uma aquisição normal e uma de cada das duas classes de falha. Você pode fixar 10 formas de dividir os grupos. Não faça aleatório.

**Comment by lucioventurim** [comment]
criado um groupkfold customizado que garante ao menos um exemplo de cada classe na fold de treinamento. a acurácia do knn reduziu em torno de 10%, já o random forest não houve diferença significativa.

**Comment by fboldt** [comment]
Isso não ficou legal: X_train = [X[i] for i in train_index]
Não use X e y como listas. Use-os como numpy arrays.
Assim você pode usar a notação X_train = X[train_index].
Além de mais legível, é mais eficiente.

**Comment by lucioventurim** [comment]
alterado para numpy arrays
