### ISSUE TITLE
Cálculos de acurácia e f1 dentro do código de experimento

### ISSUE THREAD

**Issue by fboldt** [lucioventurim/ISIE_2021#7]
Quando você calcula a acurácia e a f1 dentro do código de experimento, este fica muito poluído.
Seria melhor você rodar os experimentos e salvá-los em um arquivo.
Depois de rodados os experimentos e salvas as predições em um arquivo, você roda um módulo para compilar os resultados.
Este módulo calcularia acurácias e outras métricas.

**Comment by lucioventurim** [comment]
incluído arquivo metrics em utils para o cálculo das métricas direto dos arquivos salvos
